### ISSUE TITLE
Type GNetworkMonitorBase has not been resolved (GenerateLibs.fsx error)

### ISSUE THREAD

**Issue by MicrogamerCz** [gircore/gir.core#1131]
I was trying to build Gir.Core, but I can't even generate the libs due to the following error:

```
[20:19:33 ERR] Exception occured: One or more errors occurred. (The type GNetworkMonitorBase / ?? has not been resolved.)
System.AggregateException: One or more errors occurred. (The type GNetworkMonitorBase / ?? has not been resolved.)
 ---> System.InvalidOperationException: The type GNetworkMonitorBase / ?? has not been resolved.
   at GirLoader.Output.TypeReference.GetResolvedType() in /home/micro/Dokumenty/Projects/gir.core/src/Generation/GirLoader/Output/TypeReference.cs:line 27
   at GirLoader.Output.Field.GirModel.Field.get_AnyTypeOrCallback() in /home/micro/Dokumenty/Projects/gir.core/src/Generation/GirLoader/Output/Field.GirModel.cs:line 24
   at Generator.Renderer.Internal.UntypedRecordData.<>c.<Render>b__0_0(Field x) in /home/micro/Dokumenty/Projects/gir.core/src/Generation/Generator/Renderer/Internal/UntypedRecordData.cs:line 27
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at JoinString.Join(IEnumerable`1 ie, String separator) in /home/micro/Dokumenty/Projects/gir.core/src/Generation/Generator/Helper/JoinString.cs:line 6
   at Generator.Renderer.Internal.UntypedRecordData.Render(Record record) in /home/micro/Dokumenty/Projects/gir.core/src/Generation/Generator/Renderer/Internal/UntypedRecordData.cs:line 11
   at Generator.Generator.Internal.UntypedRecordData.Generate(Record obj) in /home/micro/Dokumenty/Projects/gir.core/src/Generation/Generator/Generator/Internal/UntypedRecordData.cs:line 19
   at Generator.Records.Generate(IEnumerable`1 records, String path) in /home/micro/Dokumenty/Projects/gir.core/src/Generation/Generator/Records.cs:line 50
   at GirTool.PlatformGenerator.Generate(Namespace namespace, String path) in /home/micro/Dokumenty/Projects/gir.core/src/Generation/GirTool/PlatformGenerator.cs:line 23
   at GirTool.GenerateCommand.<>c__DisplayClass0_0.<Execute>b__0(Namespace x) in /home/micro/Dokumenty/Projects/gir.core/src/Generation/GirTool/GenerateCommand.cs:line 36
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at GirTool.GenerateCommand.Execute(String[] input, String output, String searchPathLinux, String searchPathMacos, String searchPathWindows, Boolean dis
[output.txt](https://github.com/user-attachments/files/17480771/output.txt)
ableAsync, LogLevel logLevel, InvocationContext invocationContext) in /home/micro/Dokumenty/Projects/gir.core/src/Generation/GirTool/GenerateCommand.cs:line 36
```

The entire log file:
[output.txt](https://github.com/user-attachments/files/17480773/output.txt)

**Comment by badcel** [comment]
Can you provide all the commands you used which lead to the problem?

please start with a clean checkout of the  repository.

if you follow the build instructions in the readme it should work.

**Comment by MicrogamerCz** [comment]
I followed the instructions to the point... it works now. Sorry 😥
