### ISSUE TITLE
Unable to load shared library 'Gst' or one of its dependencies

### ISSUE THREAD

**Issue by KirMozor** [gircore/gir.core#796]
I know my question may not seem like I know how to google, but I've been looking for a solution for two days and can't find one.
I need to install the Gst library for GStreamer, but I can't find the package for ArchLinux, the error is as follows:

```
> ./RiderProjects/Yamux/Yamux/bin/Debug/net7.0/Yamux
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'Gst' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/Gst.so: cannot open shared object file: No such file or directory
/home/user/RiderProjects/Yamux/Yamux/bin/Debug/net7.0/Gst.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/libGst.so: cannot open shared object file: No such file or directory
/home/user/RiderProjects/Yamux/Yamux/bin/Debug/net7.0/libGst.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/Gst: cannot open shared object file: No such file or directory
/home/user/RiderProjects/Yamux/Yamux/bin/Debug/net7.0/Gst: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/libGst: cannot open shared object file: No such file or directory
/home/user/RiderProjects/Yamux/Yamux/bin/Debug/net7.0/libGst: cannot open shared object file: No such file or directory

   at Gst.Internal.Functions.Init(IntPtr& argc, String[] argv)
   at Gst.Application.Init()
   at Yamux.Program.Main(String[] args) in /home/user/RiderProjects/Yamux/Yamux/Program.cs:line 11
[1]    11005 IOT instruction (core dumped)  ./RiderProjects/Yamux/Yamux/bin/Debug/net7.0/Yamux
```
Code:
```
using System;
using System.Net;
using Gst;

namespace Yamux
{
    class Program
    {
        static void Main(string[] args)
        {
            Application.Init(); // Error

            // Create the elements
            var playbin = ElementFactory.Make("playbin", "playbin");
            var volume = ElementFactory.Make("volume", "volume");

            // Set the uri of the audio to play
            playbin["uri"] = "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3";

            // Link the elements
            playbin.Link(volume);

            // Start playing the audio
            playbin.SetState(State.Playing);

            // Wait for user input to control the audio
            while (true)
            {
                Console.WriteLine("Enter a command (play, pause, volume up, volume down, exit):");
                var command = Console.ReadLine().ToLower();

                switch (command)
                {
                    case "play":
                        playbin.SetState(State.Playing);
                        break;
                    case "pause":
                        playbin.SetState(State.Paused);
                        break;
                    case "volume up":
                        var volumeLevel = (double)volume["volume"] + 0.1;
                        volume["volume"] = Math.Min(volumeLevel, 10.0);
                        break;
                    case "volume down":
                        volumeLevel = (double)volume["volume"] - 0.1;
                        volume["volume"] = Math.Max(volumeLevel, 0.0);
                        break;
                    case "exit":
                        playbin.SetState(State.Null);
                        Environment.Exit(0);
                        break;
                }
            }
        }
    }
}
```

**Comment by cameronwhite** [comment]
Does adding `Gst.Module.Initialize()` first work?
I think for Gtk, Adwaita etc the `Application.Init()` calls do this for you, but perhaps not Gst

**Comment by badcel** [comment]
@cameronwhite you are right, the sample is a bit misleading here as the call is [one level up in the sample](https://github.com/gircore/gir.core/blob/ef6b2288b860ed5074847f6ff2bee32dd28eac4d/src/Samples/Gst-1.0/VideoPlayback/Program.cs#L7).

Additionally the [Application class](https://github.com/gircore/gir.core/blob/ef6b2288b860ed5074847f6ff2bee32dd28eac4d/src/Libs/Gst-1.0/Public/Application.Static.cs#L5) is pretty old code as there is no application class in Gst. I added it some day manually which is plain wrong. I created issue #797 for this.

@KirMozor If the advice from @cameronwhite is not fixing it for you let us know.

**Comment by KirMozor** [comment]
Thanks for the help, it all worked!
By the way, another question, how do you make the volume control?
Because that code doesn't adjust it

**Comment by badcel** [comment]
What do you mean by volume control?

**Comment by KirMozor** [comment]
Lowering and raising the volume

**Comment by badcel** [comment]
Actually I don't know which control you mean but I'm not familiar with all available controls.

If you can point out the C API you need we can check if it is available.
