### ISSUE TITLE
Garbage Collection frees needed objects

### ISSUE THREAD

**Issue by firox263** [gircore/gir.core#82]
We have several instances where delegates and callbacks get garbage collected when the computer is low on RAM. A typical error message looks something like this:

```
Process terminated. A callback was made on a garbage collected delegate of type 'GObject!GObject.WeakNotify::Invoke'.
   at Gtk.Global.main()
   at Gtk.Global.main()
   at Gtk.Global.Main()
   at GtkDemo.Program.Main(System.String[])
```

Once #52 is merged, I will try look into this along with some other changes to lifecycle code (e.g. ToggleRefs), so not very pressing at the moment.

**Comment by firox263** [comment]
Reopening as this is still present in `develop` and in #127.

Let's try and address this as part of #119.
