### ISSUE TITLE
Gtk.ListBox.SetHeaderFunc() fails with NullReferenceException

### ISSUE THREAD

**Issue by fsobolev** [gircore/gir.core#947]
Using [Gtk.ListBox.SetHeaderFunc](https://docs.gtk.org/gtk4/method.ListBox.set_header_func.html) causes crash:

```
Unhandled exception. System.NullReferenceException: Failed to wrap handle as type <Gtk.ListBoxRow>. Null handle passed to WrapHandle.
   at GObject.Internal.ObjectWrapper.WrapHandle[T](IntPtr handle, Boolean ownedRef)
   at Gtk.Internal.ListBoxUpdateHeaderFuncNotifiedHandler.<.ctor>b__4_0(IntPtr row, IntPtr before, IntPtr userData)
```

Tried this sample with both gir.core 0.4.0 and 0.5.0-preview1:

```csharp
public class Program
{
	private readonly Gtk.Application _app;
	private readonly Gtk.ListBoxUpdateHeaderFunc _headerFunc;
	
	private static void Main(string[] args) => new Program().Run();
	
	private Program()
	{
		_app = Gtk.Application.New("org.gircore.test", Gio.ApplicationFlags.DefaultFlags);
		_headerFunc = (row, _) => row.SetHeader(Gtk.Label.New("Header"));
		_app.OnActivate += (sender, e) =>
		{
			// Window
			var win = Gtk.ApplicationWindow.New(_app);
			win.SetDefaultSize(300, 300);
			var listbox = Gtk.ListBox.New();
			listbox.Append(Gtk.Label.New("Test"));
			listbox.SetHeaderFunc(_headerFunc);
			win.SetChild(listbox);
			_app.AddWindow(win);
			win.Present();
		};
	}
	
	private void Run()
	{
		try
		{
			_app.Run();
		}
		catch (Exception ex)
		{
			Console.WriteLine(ex);
		}
	}
}
```

**Comment by badcel** [comment]
Thank you for the report. The fix will be part of the next preview release.
